import express from "express";
import fs from "fs";
import path from "path";
import logger from "../logger.js";

const router = express.Router();

// Load pretrained logistic model (weights, bias, scalers) – generated by train-orderflow.ts
let model: { weights: number[]; bias: number; mean: number[]; std: number[] } | null = null;
const modelPath = path.resolve(process.cwd(), "orderflow_model.json");
if (fs.existsSync(modelPath)) {
  try {
    model = JSON.parse(fs.readFileSync(modelPath, "utf8"));
    logger.info({ path: modelPath }, "[orderflow] Model loaded");
  } catch (e) {
    logger.warn({ err: e }, "[orderflow] Failed to parse model");
  }
}

/** Predict probability of upward move given imbalance and depth metrics. */
router.post("/predict", (req, res) => {
  if (!model) return res.status(500).json({ success: false, error: "Model not available" });
  const { imb, bidSum, askSum, bid1, ask1, ltp } = req.body || {};
  if ([imb, bidSum, askSum, bid1, ask1, ltp].some((v) => v === undefined)) {
    return res.status(400).json({ success: false, error: "Missing required fields" });
  }
  // Feature vector – same order as training: [imb, bidSum, askSum, bid1, ask1, ltp]
  let features = [imb, bidSum, askSum, bid1, ask1, ltp];
  // z-score with the model's stored scalers (training normalized features)
  features = features.map((v, i) => (v - (model!.mean[i] ?? 0)) / (model!.std[i] ?? 1));
  const z = features.reduce((acc, v, i) => acc + (model!.weights[i] ?? 0) * v, model!.bias);
  const probUp = 1 / (1 + Math.exp(-z));
  const prediction = probUp > 0.6 ? "UP" : "DOWN";
  res.json({ success: true, probUp, prediction });
});

export default router;
